### ISSUE TITLE
`as.tibble()` is deprecated as of tibble 2.0.0.

### ISSUE THREAD

**Issue by kerry-conlin** [ropensci/nomisr#23]
Hi,

Thanks for the package, it's very useful. I'm a new R user and noticed that when I try to use the nomis_codelist() function it says that `as.tibble()` is deprecated as of tibble 2.0.0.

This is what I ran:
codes <- nomis_codelist('NM_1608_1', 'geography')

And this is the error message:
`as.tibble()` is deprecated as of tibble 2.0.0.
Please use `as_tibble()` instead.
The signature and semantics have changed, see `?as_tibble`.

Thank you!
Kerry

**Comment by evanodell** [comment]
That warning shouldn't effect the result, although I'll try to get an update on CRAN soon. In the meantime the development version has up-to-date underlying code.

**Comment by kerry-conlin** [comment]
Thanks for responding! I see that now. Appreciate it. Kerry
