### ISSUE TITLE
Write JOSS paper

### ISSUE THREAD

**Issue by evanodell** [ropensci/nomisr#4]
http://joss.theoj.org/

**Comment by rgangu** [comment]
Has this been started/worked on yet?

**Comment by evanodell** [comment]
No it has not.

**Comment by rgangu** [comment]
Do we have enough information to potentially get started?

**Comment by evanodell** [comment]
I've written something up in 432fe43, I had not realised how short JOSS papers typically are.

**Comment by evanodell** [comment]
Accepted and published: https://doi.org/10.21105/joss.00859
