### ISSUE TITLE
Appveyor badge and webhook

### ISSUE THREAD

**Issue by maelle** [ropensci/nomisr#6]
:wave: @evanodell! 

* Could you please update Appveyor badge in the README so that it points to https://ci.appveyor.com/project/evanodell/nomisr ? We no longer transfer Appveyor builds at the moment because it seems to lead to more problems.

* That said I see your webhook is broken (kind of problems we hope to avoid more :-) ), which happened randomly to repos of mine as well. [Hooks](https://github.com/ropensci/nomisr/settings/hooks) (I see there might be an issue with the Zenodo one as well?), [Appveyor hook](https://github.com/ropensci/nomisr/settings/hooks/20568054) You'll see deliveries have consistently failed in the recent past. Please email  team@appveyor.com about this and mention this info about the latest delivery
    * X-GitHub-Delivery: 10b1c890-44b6-11e8-813f-3d20e965dcfa
    * 2018-04-20 18:15:38

Thanks!

**Comment by maelle** [comment]
Maybe try that first (email received this night from Appveyor)

* New commit and push (the "account" was blocked, unclear to me whether they mean Appveyor or GitHub...)

*  If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically.

 *   If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account.

**Comment by evanodell** [comment]
I've changed where the badges pointed in 0c1106c and reset some of the git hooks, that seems to have fixed these issues.

**Comment by maelle** [comment]
Awesome thanks a lot!
