### ISSUE TITLE
release notes and news

### ISSUE THREAD

**Issue by sckott** [ropensci/nomisr#9]
hi! looks like you've been putting some news items in release notes https://github.com/ropensci/nomisr/releases but not all, e.g., your most recent v0.4 news items aren't in a release. can you try to tag each CRAN release and put news items for that version associated with the tag? thanks!

**Comment by evanodell** [comment]
Thanks for the reminder, forgot to do that: https://github.com/ropensci/nomisr/releases/tag/v0.4.0
